server:
  port: 8088

logging:
  level:
    org.springframework: debug
spring:
  messages:
    basename: messages

  devtools:
    livereload:
      enabled: true

  security:
    user:
      name: username
      password: 1234

management:
  endpoints:
    web:
      exposure:
        include: "*"
